status: Bail out early on image pull failures
Previously, if the user provides the wrong image tag, the CLI will be
stuck waiting for the pods that will never come up, like so:

```
$ ./cilium install --version 1.9.1 --context gke_cilium-dev_us-west1-a_chris-1-cluster
🔮 Auto-detected Kubernetes kind: GKE
🔮 Auto-detected cluster name: gke-cilium-dev-us-west1-a-chris-1-cluster
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: gke
✅ Detected GKE native routing CIDR: 10.52.0.0/14
🚀 Creating Resource quotas...
🔑 Found existing CA in secret cilium-ca
🔑 Generating certificates for Hubble...
2021/01/21 18:21:14 [INFO] generate received request
2021/01/21 18:21:14 [INFO] received CSR
2021/01/21 18:21:14 [INFO] generating key: ecdsa-256
2021/01/21 18:21:14 [INFO] encoded CSR
2021/01/21 18:21:14 [INFO] signed certificate with serial number
55772961565812171121429481033223530954515825728
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap...
🚀 Creating GKE Node Init DaemonSet...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
^C
```

Eventually, the CLI will timeout, but this could potentially be a waste
of time since we can know this will never converge to a successful case.

This commit adds functionality to bail out early if we detect image pull
failures in any of the pods' container statuses. Note, this only checks
a given pod's first container status (either an init container or normal
container, depending on if there's an init container). If the first
container status is an image pull failure, then we bail out. The reason
we only check the first container is because of the ordering in which
containers are started. If the first container isn't started, the second
will stay in pending state. Thus, it is sufficient to simply check the
first container.

This is what it looks like to bail out early:

```
$ ./cilium install --version 1.9.1
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.10.0"
🔮 Auto-detected cluster name: kind-kind
🔮 Auto-detected IPAM mode: kubernetes
🔑 Found existing CA in secret cilium-ca
🔑 Generating certificates for Hubble...
2021/01/26 19:16:35 [INFO] generate received request
2021/01/26 19:16:35 [INFO] received CSR
2021/01/26 19:16:35 [INFO] generating key: ecdsa-256
2021/01/26 19:16:35 [INFO] encoded CSR
2021/01/26 19:16:35 [INFO] signed certificate with serial number 707080097620757187800803383760378208473180677199
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         2 errors, 2 warnings
 \__/¯¯\__/    Operator:       2 errors, 1 warnings
 /¯¯\__/¯¯\    Hubble:         1 warnings
 \__/¯¯\__/    ClusterMesh:    1 warnings
    \__/

DaemonSet         cilium                   Desired: 2, Unavailable: 2/2
Deployment        cilium-operator          Desired: 1, Unavailable: 1/1
Containers:       cilium                   Pending: 2
                  cilium-operator          Pending: 1
Image versions    cilium                   quay.io/cilium/cilium:1.9.1: 2
                  cilium-operator          quay.io/cilium/operator-generic:1.9.1: 1
Errors:           cilium                   cilium                              2 pods of DaemonSet cilium are not ready
                  cilium                   cilium-7xmkl                        Pod image pull failed
                  cilium-operator          cilium-operator                     1 pods of DaemonSet cilium-operator are not ready
                  cilium-operator          cilium-operator-7cd4fc5ffd-jt9sz    Pod image pull failed
Warnings:         cilium                   cilium-7xmkl                        Pod is pending
                  cilium                   cilium-bmxw7                        Pod is pending
                  cilium-operator          cilium-operator-7cd4fc5ffd-jt9sz    Pod is pending
                  hubble-relay             hubble-relay                        Relay is not deployed
                  clustermesh-apiserver    clustermesh-apiserver               ClusterMesh is not deployed

Error: Unable to install Cilium:  Pod image pull failed
```

Signed-off-by: Chris Tarazi <chris@isovalent.com>