ci: refresh login before aks cleanup
Since somewhat recently aks credential seems to be only valid for 5min.
For instance here is an error fetched on an action failure when trying
to cleanup a cluster.

```
ERROR: AADSTS700024: Client assertion is not within its valid time range. Current time: 2024-04-11T18:28:00.5441148Z, assertion valid from 2024-04-11T18:01:56.0000000Z, expiry time of assertion 2024-04-11T18:06:56.0000000Z.
```

This commit solves that by login in again right before we issue the
cleanup task.

Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>