status: Bail out early on image pull failures
Previously, if the user provides the wrong image tag, the CLI will be
stuck waiting for the pods that will never come up, like so:

```
$ ./cilium install --version 1.9.1 --context gke_cilium-dev_us-west1-a_chris-1-cluster
🔮 Auto-detected Kubernetes kind: GKE
🔮 Auto-detected cluster name: gke-cilium-dev-us-west1-a-chris-1-cluster
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: gke
✅ Detected GKE native routing CIDR: 10.52.0.0/14
🚀 Creating Resource quotas...
🔑 Found existing CA in secret cilium-ca
🔑 Generating certificates for Hubble...
2021/01/21 18:21:14 [INFO] generate received request
2021/01/21 18:21:14 [INFO] received CSR
2021/01/21 18:21:14 [INFO] generating key: ecdsa-256
2021/01/21 18:21:14 [INFO] encoded CSR
2021/01/21 18:21:14 [INFO] signed certificate with serial number
55772961565812171121429481033223530954515825728
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap...
🚀 Creating GKE Node Init DaemonSet...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
^C
```

Eventually, the CLI will timeout, but this could potentially be a waste
of time since we can know this will never converge to a successful case.

This commit adds functionality to bail out early if we detect image pull
failures in the Cilium pod's init container statuses.

This is what it looks like to bail out early:

```
$ ./cilium install --version 1.9.1 --context gke_cilium-dev_us-west1-a_chris-1-cluster
🔮 Auto-detected Kubernetes kind: GKE
🔮 Auto-detected cluster name: gke-cilium-dev-us-west1-a-chris-1-cluster
🔮 Auto-detected IPAM mode: kubernetes
🔮 Auto-detected datapath mode: gke
✅ Detected GKE native routing CIDR: 10.52.0.0/14
🚀 Creating Resource quotas...
🔑 Found existing CA in secret cilium-ca
🔑 Generating certificates for Hubble...
2021/01/21 18:30:08 [INFO] generate received request
2021/01/21 18:30:08 [INFO] received CSR
2021/01/21 18:30:08 [INFO] generating key: ecdsa-256
2021/01/21 18:30:08 [INFO] encoded CSR
2021/01/21 18:30:08 [INFO] signed certificate with serial number 528084987724792402735143004944875938198072101744
🚀 Creating Service accounts...
🚀 Creating Cluster roles...
🚀 Creating ConfigMap...
🚀 Creating GKE Node Init DaemonSet...
🚀 Creating Agent DaemonSet...
🚀 Creating Operator Deployment...
⌛ Waiting for Cilium to be installed...
    /¯¯\
 /¯¯\__/¯¯\    Cilium:         1 errors
 \__/¯¯\__/    Operator:       OK
 /¯¯\__/¯¯\    Hubble:         OK
 \__/¯¯\__/    ClusterMesh:    OK
    \__/

DaemonSet    cilium    Desired: 1, Unavailable: 1/1
Errors:      cilium    cilium    1 pods of DaemonSet cilium are not ready

Error: image pull failed
```

Signed-off-by: Chris Tarazi <chris@isovalent.com>