connectivity/check: support running on Cilium 1.8
Running `cilium connectivity test` on a Cilium 1.8 cluster currently
fails with:

    Error: Connectivity test failed: unable to list external workloads: the server could not find the requested resource (get ciliumexternalworkloads.cilium.io)
    Error: Process completed with exit code 1.

This is because support for external workloads was only introduced in
Cilium 1.9.

Fix this by treating such errors as non-fatal in deployment validation.
This will allow to run connectivity checks against Cilium 1.8 as well.

Reported-by: André Martins <andre@cilium.io>
Signed-off-by: Tobias Klauser <tobias@cilium.io>